### ISSUE TITLE
Update devDependencies?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/ordem#10]
This is a(nother) **_Zero Dependencies**_ module. but we do have a few devDeps... should we keep them up to date?

**Comment by iteles** [comment]
I would suggest we add in a line in the [How?](https://github.com/dwyl/ordem#how) section telling people to run `npm update --save-dev` to make sure the devDependencies are up to date.
That takes the onus off us as well as maybe teaching people a new thing.

**Comment by nelsonic** [comment]
Sure, good suggestion, but I'm referring to this: https://david-dm.org/dwyl/ordem#info=devDependencies
And if we include the badge in the repo, people will think the _module_ is using out of date deps...

**Comment by iteles** [comment]
Agreed, then we should keep them up-to-date. Should be a monthly check-task on all 'our' modules :stuck_out_tongue:
